use std::{
    fs::{self, OpenOptions},
    io::Write,
    os::unix::fs::{OpenOptionsExt, PermissionsExt},
    path::{Path, PathBuf},
};

use serde::Serialize;
use tauri::{AppHandle, Manager, WebviewWindow, webview::Cookie};
use thiserror::Error;

const YOUTUBE_SESSION_FILE: &str = "youtube-cookies.txt";
const ACCOUNT_COOKIE_NAMES: &[&str] = &["SAPISID", "__Secure-3PAPISID", "LOGIN_INFO"];

#[derive(Clone, Copy, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct YouTubeAuthStatus {
    pub connected: bool,
}

#[derive(Debug, Error)]
pub enum YouTubeAuthError {
    #[error("the YouTube login window is not open")]
    LoginWindowNotOpen,

    #[error("finish signing in to YouTube before using this session")]
    NotSignedIn,

    #[error("could not access the YouTube login session: {0}")]
    Webview(String),

    #[error("could not store the YouTube login session: {0}")]
    Storage(String),
}

#[derive(Clone, Debug)]
pub(crate) struct SessionCookie {
    domain: String,
    path: String,
    secure: bool,
    http_only: bool,
    expires_unix: i64,
    name: String,
    value: String,
}

impl SessionCookie {
    fn from_webview(cookie: &Cookie<'_>) -> Self {
        Self {
            domain: cookie.domain().unwrap_or(".youtube.com").to_owned(),
            path: cookie.path().unwrap_or("/").to_owned(),
            secure: cookie.secure().unwrap_or(false),
            http_only: cookie.http_only().unwrap_or(false),
            expires_unix: cookie
                .expires_datetime()
                .map(|expires| expires.unix_timestamp().max(0))
                .unwrap_or(0),
            name: cookie.name().to_owned(),
            value: cookie.value().to_owned(),
        }
    }

    fn is_well_formed(&self) -> bool {
        !self.domain.contains(['\t', '\r', '\n'])
            && !self.path.contains(['\t', '\r', '\n'])
            && !self.name.contains(['\t', '\r', '\n'])
            && !self.value.contains(['\t', '\r', '\n'])
    }
}

pub fn session_cookie_path(app: &AppHandle) -> Result<PathBuf, YouTubeAuthError> {
    app.path()
        .app_data_dir()
        .map(|directory| directory.join(YOUTUBE_SESSION_FILE))
        .map_err(|error| YouTubeAuthError::Storage(error.to_string()))
}

pub fn session_exists(path: &Path) -> bool {
    path.is_file()
}

pub fn save_session_from_window(
    window: &WebviewWindow,
    path: &Path,
) -> Result<(), YouTubeAuthError> {
    let cookies = window
        .cookies()
        .map_err(|error| YouTubeAuthError::Webview(error.to_string()))?
        .iter()
        .filter(|cookie| cookie.domain().is_some_and(is_youtube_cookie_domain))
        .map(SessionCookie::from_webview)
        .filter(SessionCookie::is_well_formed)
        .collect::<Vec<_>>();
    tracing::debug!(cookies = cookies.len(), "YouTube session cookies collected");

    if !has_youtube_account_session(&cookies) {
        tracing::error!("YouTube account session cookie was not found");
        return Err(YouTubeAuthError::NotSignedIn);
    }

    write_session_file(path, &cookies)
}

pub fn disconnect_session(app: &AppHandle, path: &Path) -> Result<(), YouTubeAuthError> {
    tracing::debug!("removing local YouTube session");
    match fs::remove_file(path) {
        Ok(()) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => return Err(YouTubeAuthError::Storage(error.to_string())),
    }

    if let Some(window) = app.get_webview_window("youtube-auth") {
        window
            .clear_all_browsing_data()
            .map_err(|error| YouTubeAuthError::Webview(error.to_string()))?;
        window
            .close()
            .map_err(|error| YouTubeAuthError::Webview(error.to_string()))?;
    }

    Ok(())
}

fn write_session_file(path: &Path, cookies: &[SessionCookie]) -> Result<(), YouTubeAuthError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| YouTubeAuthError::Storage(error.to_string()))?;
    }

    let mut file = OpenOptions::new()
        .create(true)
        .truncate(true)
        .write(true)
        .mode(0o600)
        .open(path)
        .map_err(|error| YouTubeAuthError::Storage(error.to_string()))?;
    file.set_permissions(fs::Permissions::from_mode(0o600))
        .map_err(|error| YouTubeAuthError::Storage(error.to_string()))?;
    writeln!(file, "# Netscape HTTP Cookie File")
        .and_then(|()| writeln!(file, "# Generated by G Music for local yt-dlp playback."))
        .map_err(|error| YouTubeAuthError::Storage(error.to_string()))?;
    for cookie in cookies {
        writeln!(file, "{}", format_netscape_cookie(cookie))
            .map_err(|error| YouTubeAuthError::Storage(error.to_string()))?;
    }
    file.flush()
        .map_err(|error| YouTubeAuthError::Storage(error.to_string()))?;
    tracing::debug!(cookies = cookies.len(), "YouTube session file written");
    Ok(())
}

pub(crate) fn format_netscape_cookie(cookie: &SessionCookie) -> String {
    let domain = if cookie.http_only {
        format!("#HttpOnly_{}", cookie.domain)
    } else {
        cookie.domain.clone()
    };
    let include_subdomains = if cookie.domain.starts_with('.') {
        "TRUE"
    } else {
        "FALSE"
    };
    let secure = if cookie.secure { "TRUE" } else { "FALSE" };

    format!(
        "{domain}\t{include_subdomains}\t{}\t{secure}\t{}\t{}\t{}",
        cookie.path, cookie.expires_unix, cookie.name, cookie.value
    )
}

pub(crate) fn has_youtube_account_session(cookies: &[SessionCookie]) -> bool {
    cookies.iter().any(|cookie| {
        ACCOUNT_COOKIE_NAMES.contains(&cookie.name.as_str()) && !cookie.value.is_empty()
    })
}

pub(crate) fn is_youtube_cookie_domain(domain: &str) -> bool {
    let domain = domain.trim_start_matches('.').to_ascii_lowercase();
    domain == "youtube.com" || domain.ends_with(".youtube.com")
}

#[cfg(test)]
mod tests {
    use super::{
        SessionCookie, format_netscape_cookie, has_youtube_account_session,
        is_youtube_cookie_domain,
    };

    fn cookie(name: &str, value: &str) -> SessionCookie {
        SessionCookie {
            domain: ".youtube.com".into(),
            path: "/".into(),
            secure: true,
            http_only: true,
            expires_unix: 1_900_000_000,
            name: name.into(),
            value: value.into(),
        }
    }

    #[test]
    fn formats_secure_http_only_cookies_for_yt_dlp() {
        assert_eq!(
            format_netscape_cookie(&cookie("SAPISID", "secret")),
            "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1900000000\tSAPISID\tsecret"
        );
    }

    #[test]
    fn identifies_an_authenticated_youtube_cookie_set() {
        assert!(has_youtube_account_session(&[cookie("SAPISID", "secret")]));
        assert!(!has_youtube_account_session(&[cookie(
            "PREF",
            "theme=dark"
        )]));
    }

    #[test]
    fn accepts_youtube_cookie_domains_with_a_leading_dot() {
        assert!(is_youtube_cookie_domain("youtube.com"));
        assert!(is_youtube_cookie_domain(".youtube.com"));
        assert!(is_youtube_cookie_domain(".music.youtube.com"));
        assert!(!is_youtube_cookie_domain("accounts.google.com"));
        assert!(!is_youtube_cookie_domain("notyoutube.com"));
    }
}
